on: push

jobs:
  build_and_publish:
    name: "build and publish"
    steps:
    - name: tag
      uses: "actions/bin/filter@master"
      args: "tag"
    - name: "build"
      uses: "docker://lambci/lambda:build-nodejs10.x"
      runs: ["./scripts/build.sh"]
    - name: "publish"
      uses: "actions/npm@master"
      args: "publish --access public"
      secrets: ["NPM_AUTH_TOKEN"]
