on:
  push:
    tags:
    - '*'
    
jobs:
  build_and_publish:
    runs-on: [ubuntu-18.04]
    name: "build and publish"
    steps:
    - uses: actions/checkout@v1
    - name: "build"
      uses: "docker://lambci/lambda:build-nodejs10.x"
      with:
        entrypoint: "./scripts/build.sh"
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: "npm publish --access public"
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
